const express = require('express');
const userRouter= express.Router();
const {registerUser1,registerUser2,registerUser3, authUser, allUsers} =require('../controllers/userControllers');
const { protect } = require('../middleware/authMiddleware');
userRouter.route('/register/step1').post(registerUser1);
userRouter.route("/register/step2").post(registerUser2);
userRouter.route("/register/step3").post(registerUser3).get(protect,allUsers);
userRouter.route('/login').post(authUser);
//userRouter.route("/").get(protect,allUsers);
module.exports = userRouter;
